apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ypf01jqsz-nodejs 
  janus-idp.io/tekton: ypf01jqsz-nodejs
  backstage.io/kubernetes-id: ypf01jqsz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ypf01jqsz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  