apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ypf01jqsz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ypf01jqsz-nodejs 
  name: ypf01jqsz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ypf01jqsz-nodejs 
